version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../producer_deployment_package.zip .
      - cd ..
      - zip -g producer_deployment_package.zip ProduceAirbnbBookingData.py
      - cd lib
      - zip -r9 ../consumer_deployment_package.zip .
      - cd ..
      - zip -g consumer_deployment_package.zip ProcessFilteredBookings.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp producer_deployment_package.zip s3://lambda-builds-zip-vj/
      - aws s3 cp consumer_deployment_package.zip s3://lambda-builds-zip-vj/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name ProduceAirbnbBookingData --s3-bucket lambda-builds-zip-vj --s3-key producer_deployment_package.zip
      - aws lambda update-function-code --function-name ProcessFilteredBookings --s3-bucket lambda-builds-zip-vj --s3-key consumer_deployment_package.zip
      - echo "Deployment complete!"